version: '3.1'

services:
     server:
         container_name: cryptit-server
         build: ./docker/server/
         restart: always
         depends_on:
             - postgresdb
         ports:
             - 8080:80
         volumes:
             - ./server/:/var/www/html/
             - ./docker/server/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
         networks:
             - cryptit
 
     postgresdb:
         container_name: cryptit-database
         image: postgres:latest
         restart: always
         environment:
             - POSTGRES_PASSWORD=password
             - POSTGRES_USER=cryptituser
             - POSTGRES_DB=cryptitdb
         volumes:
             - ./db-data/:/var/lib/postgresql/data/
         networks:
           - cryptit
         ports:
            - 5432:5432

networks:
    cryptit: